/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brekbrek_1app_utils_SpeexEncoder */

#ifndef _Included_com_brekbrek_1app_utils_SpeexEncoder
#define _Included_com_brekbrek_1app_utils_SpeexEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brekbrek_1app_utils_SpeexEncoder
 * Method:    encode
 * Signature: (I[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_brekbrek_1app_utils_SpeexEncoder_encode
  (JNIEnv *, jclass, jint, jshortArray);

/*
 * Class:     com_brekbrek_1app_utils_SpeexEncoder
 * Method:    getSampleRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_brekbrek_1app_utils_SpeexEncoder_getSampleRate
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_brekbrek_1app_utils_SpeexEncoder
 * Method:    getFrameSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_brekbrek_1app_utils_SpeexEncoder_getFrameSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_brekbrek_1app_utils_SpeexEncoder
 * Method:    allocate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_brekbrek_1app_utils_SpeexEncoder_allocate
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     v_SpeexEncoder
 * Method:    deallocate
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_brekbrek_1app_utils_SpeexEncoder_deallocate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif